# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ master, develop ]

jobs:
  build:
    name: build
    env:
      ANDROID_API_LEVEL: 30
      ANDROID_SDK_BUILD_TOOLS_VERSION: 30.0.2
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64/
    runs-on: ubuntu-latest
    steps:
    - name: Checkout geniustmusicplayer
      uses: actions/checkout@v2
    # helps with GitHub runner running out of space
    - name: Free disk space
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt -y clean
    - name: Install python-for-android (P4A) dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y build-essential ccache git zlib1g-dev python3 python3-dev libncurses5:i386 libstdc++6:i386 zlib1g:i386 openjdk-8-jdk unzip ant ccache autoconf libtool libssl-dev
        sudo apt remove --purge openjdk-*-jdk
        sudo apt install openjdk-8-jdk
        pip install Cython==0.29.22
    - name: Fork and Install P4A
      run: |
        git clone https://github.com/allerter/python-for-android
        pip install -e ./python-for-android
    - name: Download Android SDK and NDK
      run: make --file python-for-android/ci/makefiles/android.mk
    - name: Build APK
      env:
        ANDROID_NDK_HOME: /usr/local/lib/android/sdk/android-ndk
      run: |
        cd geniustmusicplayer
        p4a apk \
            --enable-androidx \
            --ndk_dir $ANDROID_NDK_HOME \
            --ndk_api 21
            --android_api $ANDROID_API_LEVEL \
            --bootstrap sdl2 \
            --dist_name geniustmusicplayer \
            --name="GeniusT Music Player" \
            --version 0.8 \
            --package org.allerter.geniustmusicplayer \
            --requirements python3,kivy==2.0.0,https://github.com/kivymd/KivyMD/archive/c792038.zip,android,sdl2_ttf==2.0.15,requests,urllib3,idna,chardet,oscpy,pillow \
            --orientation portrait \
            --window \
            --private ./ \
            --permission INTERNET \
            --permission ACCESS_NETWORK_STATE \
            --permission FOREGROUND_SERVICE \
            --service gtplayer:./service.py \
            --depend "com.android.support:support-compat:28.0.0" \
            --depend "androidx.legacy:legacy-support-v4:1.0.0" \
            --depend "com.google.code.gson:gson:2.8.5" \
            --presplash-lottie ./images/presplash.json \
            --presplash-color white \
            --icon ./images/icon.png \
            --add-aar ./spotify-auth-release-1.2.3.aar \
            --add-aar ./genius-auth-release-1.2.4.aar \
            --intent-filters ./intent_filters.xml
    - uses: actions/upload-artifact@v1
      with:
        name: geniustmusicplayer-debug.apk
        path: build-bin
