# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ master, develop ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files
      uses: actions/checkout@v2
    # helps with GitHub runner getting out of space
    - name: Free disk space
      run: |
        df -h
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt -y clean
        docker rmi $(docker image ls -aq)
        df -h
    - name: Build apk
      run: |
        mkdir -p build-bin
        docker build --tag=p4a --file Dockerfile .

    - uses: actions/upload-artifact@v1
      with:
        name: geniustmusicplayer-debug.apk
        path: build-bin
